services:

    dynamodb-local:
        # image: amazon/dynamodb-local:latest
        build: .
        container_name: dynamodb-local
        user: root
        working_dir: /home/dynamodblocal
        environment:
            AWS_ACCESS_KEY_ID: local
            AWS_SECRET_ACCESS_KEY: local
            AWS_DEFAULT_REGION: "us-west-2"
            AWS_PAGER: ""
            AWS_ENDPOINT_URL_DYNAMODB: "http://localhost:8000"
            RESET_DB: "false" # "true" or "false"
        volumes:
            - ./dbdata:/home/dynamodblocal/data
            - ./init:/home/dynamodblocal/init
        ports:
            - 8000:8000

    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        container_name: dynamodb-admin
        environment:
            DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
            AWS_REGION: "us-west-2"
            AWS_ACCESS_KEY_ID: local
            AWS_SECRET_ACCESS_KEY: local
            AWS_DEFAULT_REGION: "us-west-2"
            AWS_PAGER: ""
        depends_on:
            - dynamodb-local
        ports:
            - "8001:8001"
    auth-api:
        build: ./auth-cli
        container_name: auth-cli
        environment:
            DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
            JWT_SECRET_KEY: "seu-segredo-super-secreto"
            # ðŸ’¡ ADICIONE ESTAS TRÃŠS LINHAS:
            AWS_ACCESS_KEY_ID: local
            AWS_SECRET_ACCESS_KEY: local
            AWS_REGION: "us-west-2"
        depends_on:
            - dynamodb-local
            - dynamodb-admin